"""add banner fields to event

Revision ID: 3b52849caf54
Revises: 56c664645985
Create Date: 2026-08-02 01:28:47.580598

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '3b52849caf54'
down_revision: Union[str, Sequence[str], None] = '56c664645985'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('banner_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('event', sa.Column('banner_storage_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event', 'banner_storage_path')
    op.drop_column('event', 'banner_url')
    # ### end Alembic commands ###
