"""add fraud reason and score to order

Revision ID: 4588242ad661
Revises: 645472373c36
Create Date: 2026-07-31 07:15:30.021681

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '4588242ad661'
down_revision: Union[str, Sequence[str], None] = '645472373c36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('fraud_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('order', sa.Column('fraud_score', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'fraud_score')
    op.drop_column('order', 'fraud_reason')
    # ### end Alembic commands ###
