"""expand event and ticket tier fields

Revision ID: 505cc92acaf4
Revises: b169a40a0dff
Create Date: 2026-07-22 22:43:38.340187

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '505cc92acaf4'
down_revision: Union[str, Sequence[str], None] = 'b169a40a0dff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('event', sa.Column('address', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('event', sa.Column('city', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('event', sa.Column('country', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('event', sa.Column('start_datetime', sa.DateTime(), nullable=False))
    op.add_column('event', sa.Column('end_datetime', sa.DateTime(), nullable=False))
    op.add_column('event', sa.Column('max_capacity', sa.Integer(), nullable=False))
    op.add_column('event', sa.Column('dress_code', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('event', sa.Column('age_restriction', sa.Integer(), nullable=True))
    op.add_column('event', sa.Column('parking_available', sa.Boolean(), nullable=False))
    op.add_column('event', sa.Column('food_available', sa.Boolean(), nullable=False))
    op.add_column('event', sa.Column('refund_policy', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('event', sa.Column('terms_accepted', sa.Boolean(), nullable=False))
    op.drop_column('event', 'date')
    op.add_column('tickettier', sa.Column('category_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('tickettier', sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('tickettier', sa.Column('total_seats', sa.Integer(), nullable=False))
    op.add_column('tickettier', sa.Column('benefits_included', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('tickettier', sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_column('tickettier', 'total_quantity')
    op.drop_column('tickettier', 'tier_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickettier', sa.Column('tier_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('tickettier', sa.Column('total_quantity', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('tickettier', 'description')
    op.drop_column('tickettier', 'benefits_included')
    op.drop_column('tickettier', 'total_seats')
    op.drop_column('tickettier', 'currency')
    op.drop_column('tickettier', 'category_name')
    op.add_column('event', sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('event', 'terms_accepted')
    op.drop_column('event', 'refund_policy')
    op.drop_column('event', 'food_available')
    op.drop_column('event', 'parking_available')
    op.drop_column('event', 'age_restriction')
    op.drop_column('event', 'dress_code')
    op.drop_column('event', 'max_capacity')
    op.drop_column('event', 'end_datetime')
    op.drop_column('event', 'start_datetime')
    op.drop_column('event', 'country')
    op.drop_column('event', 'city')
    op.drop_column('event', 'address')
    op.drop_column('event', 'category')
    # ### end Alembic commands ###
