"""split order status into payment_status and fraud_status

Revision ID: 56c664645985
Revises: a367c7059822
Create Date: 2026-07-31 11:53:00.978889

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '56c664645985'
down_revision: Union[str, Sequence[str], None] = 'a367c7059822'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('payment_status', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.drop_column('order', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('order', 'payment_status')
    # ### end Alembic commands ###
