"""split order status into payment_status and fraud_status

Revision ID: a367c7059822
Revises: 4588242ad661
Create Date: 2026-07-31 11:46:03.254096

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'a367c7059822'
down_revision: Union[str, Sequence[str], None] = '4588242ad661'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('fraud_status', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'fraud_status')
    # ### end Alembic commands ###
