"""restructure order into order and order_item

Revision ID: e84556ca1f2b
Revises: 3420a1972d97
Create Date: 2026-07-27 12:21:19.053903

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e84556ca1f2b'
down_revision: Union[str, Sequence[str], None] = '3420a1972d97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_order_ticket_tier'), 'order', type_='foreignkey')
    op.drop_column('order', 'ticket_tier_id')
    op.drop_column('order', 'quantity')
    op.drop_column('order', 'qr_code')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('qr_code', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('order', sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('order', sa.Column('ticket_tier_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('fk_order_ticket_tier'), 'order', 'tickettier', ['ticket_tier_id'], ['id'])
    # ### end Alembic commands ###
